name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: make integration
